import { useState, type FormEvent } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { BookOpen, ChevronRight, Download, LifeBuoy, Play, Search } from 'lucide-react';
import { useExpenseStore } from '@/store';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Textarea } from '@/components/ui/textarea';

const guides = [
  { title: 'Dashboard', path: '/', text: 'Balance uses every recorded transaction. Income, expenses, savings rate, and top categories use the current month. Recent Activity shows your five latest entries. Savings rate is (income minus expenses) divided by income; it can be negative. With no income, the rate is zero and Quick Stats explains that no income is recorded.' },
  { title: 'Add transaction', path: '/add-transaction', text: 'Step 1: choose Expense or Income and a positive INR amount with up to two decimal places. Step 2: choose an existing category and enter a description. Step 3: set the date and optionally repeat weekly, monthly, or yearly. Step 4: review and Save transaction. Back preserves your entries within the form. Leaving the page discards unsaved entries.' },
  { title: 'Transactions', path: '/transactions', text: 'Filter by income or expense; sort by date, amount, or description. Browse ten entries per page. Row checkboxes keep selections across pages; the header checkbox selects only the current page. Export downloads selected entries in the active filter, otherwise all filtered entries. CSV amounts are numeric INR; JSON includes currency and category names.' },
  { title: 'View, edit, and delete', path: '/transactions', text: 'Open a transaction name or its three-dot button for a detail modal. Escape or Close dismisses it. Choose Open full transaction to view its history, edit details, or delete using the confirmation dialog. Changes update your dashboard and analytics.' },
  { title: 'Analytics', path: '/charts', text: 'Choose a month. The line chart covers six calendar months ending in that month and shows income, expenses, and net savings. Empty months contribute zero. The donut includes only expenses from the chosen month. Hover or keyboard-focus a segment or legend item for its amount and percentage. The line-card download button exports the plotted totals as CSV.' },
  { title: 'Reports', path: '/reports', text: 'Select the available reporting period, review the preview, and download PDF or Excel. Reports use recorded transactions and any saved budgets. Exports are disabled when the period has no transactions. Excel includes five formatted sheets: Summary, Monthly, Categories, Budgets, and Transactions. Monetary cells are numeric, dates are typed, and descriptions wrap. Budget allocations use current saved limits prorated across calendar days. Download transaction JSON separately from Transactions for a reference copy.' },
  { title: 'Appearance and stored data', path: '/settings', text: 'Settings shows your transaction count and lets you switch light or dark mode. Transactions, budgets, preferences, and onboarding completion are saved in this browser. There is no sign-in or cross-device sync. Clearing site data, using another browser, or ending a private session can remove access to these records.' },
];
const faqs = [
  ['Why are monthly figures zero?', 'Check the transaction date and type. Dashboard uses the current calendar month; Analytics uses its selected month. Transactions can show entries from any date.'],
  ['Can I change the currency?', 'This version uses Indian rupees (INR) with Indian digit grouping, such as ₹1,23,456.78. It does not convert foreign currencies.'],
  ['Why is my export missing selected rows?', 'Export includes selected rows only within the active type filter. Clear selections to export every filtered row, or change to All types to include selections of both types.'],
  ['Where can I set a budget?', 'The current screens display saved budget usage and alerts, but do not provide a budget editor. Sample data includes budgets. Alerts appear when recorded category expenses reach their saved monthly limit.'],
  ['Does a recurring entry connect to my bank?', 'No. A repeat interval stores a schedule and next occurrence for a recorded transaction. Expenso does not connect to your bank or perform payments.'],
  ['Can I restore an exported file?', 'Exports are downloadable records. The redesigned Transactions page does not currently offer an import or restore control. Keep exported copies for reference; avoid clearing browser data if you need the live records.'],
  ['What if a category has been removed?', 'Analytics and the table retain those transaction amounts and label their category Uncategorized.'],
  ['Is this a live support service?', 'No. The form below demonstrates creating a support request locally on this page. It does not send email, open a live ticket, or contact a support team.'],
];
const walkthrough = [
  { title: 'Record sample income', text: 'Add Income of ₹50,000.00 with description “Sample salary”, an appropriate existing category, and a date in the current month. Review and save.', path: '/add-transaction' },
  { title: 'Record a sample expense', text: 'Add Expense of ₹2,500.00 with description “Sample groceries”, an appropriate existing category, and a current-month date. Leave Repeat off and save.', path: '/add-transaction' },
  { title: 'Review the entries', text: 'Open Transactions, choose All types, and sort Newest first. Open each sample entry in the modal. Select both entries and export CSV or JSON.', path: '/transactions' },
  { title: 'Read the results', text: 'Choose the current month in Analytics. These two entries contribute ₹50,000 income, ₹2,500 expenses, and ₹47,500 net savings. Their savings rate is 95%. Existing entries also affect totals.', path: '/charts' },
  { title: 'Download a report', text: 'Open Reports and choose a period containing the sample dates. Review the preview and download the PDF or Excel. Return to the dashboard to see the updated totals.', path: '/reports' },
  { title: 'Finish the practice run', text: 'If you added the examples, open their full transaction pages and delete only your “Sample salary” and “Sample groceries” entries after checking the confirmation. This guide does not add or delete records automatically.', path: '/transactions' },
];

export default function HelpPage() {
  const navigate = useNavigate();
  const [query, setQuery] = useState('');
  const [completed, setCompleted] = useState<number[]>([]);
  const [request, setRequest] = useState<{ id: string; subject: string; topic: string; message: string; createdAt: string } | null>(null);
  const [topic, setTopic] = useState('Transactions');
  const [subject, setSubject] = useState('');
  const [message, setMessage] = useState('');
  const [error, setError] = useState('');
  const matches = (text: string) => text.toLowerCase().includes(query.trim().toLowerCase());
  const filteredGuides = guides.filter(guide => matches(guide.title + ' ' + guide.text));
  const filteredFAQs = faqs.filter(faq => matches(faq.join(' ')));
  const startTour = (intro: boolean) => { navigate('/'); useExpenseStore.setState({ hasToured: false, ...(intro ? { hasOnboarded: false } : {}) }); };
  const submit = (event: FormEvent) => {
    event.preventDefault();
    if (!subject.trim() || !message.trim()) { setError('Enter a subject and describe the issue.'); return; }
    setRequest({ id: `DEMO-${crypto.randomUUID().slice(0, 8).toUpperCase()}`, subject: subject.trim(), topic, message: message.trim(), createdAt: new Date().toISOString() });
    setError('');
  };
  const downloadRequest = () => {
    const url = URL.createObjectURL(new Blob([JSON.stringify({ ...request, status: 'Local demo only - not sent' }, null, 2)], { type: 'application/json' }));
    const anchor = document.createElement('a'); anchor.href = url; anchor.download = `${request?.id}.json`; anchor.click(); setTimeout(() => URL.revokeObjectURL(url), 1000);
  };
  return <div id="tour-help" className="space-y-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="flex items-center gap-2 text-sm font-medium text-primary mb-2"><LifeBuoy className="h-4 w-4" />Expenso help centre</p><h1 className="text-3xl font-bold tracking-tight">Help & Support</h1><p className="mt-2 text-muted-foreground">Learn the workflow, find answers, and explore a sample support request.</p></div><Button onClick={() => startTour(false)}><Play className="h-4 w-4 mr-2" />Start guided tour</Button></header>
    <Card className="p-6 flex flex-wrap items-center justify-between gap-4"><div><h2 className="font-semibold">New here?</h2><p className="mt-1 text-sm text-muted-foreground">Replay the introduction or follow the practice guide below.</p></div><Button variant="outline" onClick={() => startTour(true)}>Replay welcome introduction</Button></Card>
    <nav aria-label="Help topics" className="flex flex-wrap gap-3 text-sm text-primary">{[['walkthrough', 'Sample walkthrough'], ['guides', 'Screen guides'], ['faq', 'FAQs'], ['troubleshooting', 'Troubleshooting'], ['support', 'Demo support request']].map(([id, label]) => <a key={id} href={'#' + id} className="rounded-full border bg-card px-4 py-2 hover:bg-muted">{label}</a>)}</nav>
    <section id="walkthrough" className="scroll-mt-20"><h2 className="text-xl font-semibold mb-2">A sample end-to-end workflow</h2><p className="text-sm text-muted-foreground mb-5">Practice at your own pace. Checkboxes track progress on this page only. Example amounts are illustrative; following the links will not save anything automatically.</p><div className="grid md:grid-cols-2 gap-4">{walkthrough.map((item, index) => <Card key={item.title} className="p-5"><div className="flex items-start gap-3"><input type="checkbox" aria-label={`Mark step ${index + 1} complete`} checked={completed.includes(index)} onChange={() => setCompleted(previous => previous.includes(index) ? previous.filter(i => i !== index) : [...previous, index])} className="mt-1 size-4 accent-blue-600 shrink-0" /><div><h3 className="font-medium">{index + 1}. {item.title}</h3><p className="my-2 text-sm leading-relaxed text-muted-foreground">{item.text}</p><Link to={item.path} className="inline-flex items-center text-sm text-primary hover:underline">Open screen<ChevronRight className="h-4 w-4" /></Link></div></div></Card>)}</div><p aria-live="polite" className="mt-3 text-xs text-muted-foreground">{completed.length} of {walkthrough.length} practice steps checked</p></section>
    <div className="relative"><Search className="absolute top-3 left-3 h-4 w-4 text-muted-foreground" /><Input className="pl-9 bg-card" aria-label="Search help guides and FAQs" placeholder="Search guides and FAQs..." value={query} onChange={event => setQuery(event.target.value)} /></div>
    <section id="guides" className="scroll-mt-20"><h2 className="flex items-center gap-2 text-xl font-semibold mb-4"><BookOpen className="h-5 w-5" />Screen guides</h2><div className="grid md:grid-cols-2 gap-4">{filteredGuides.map(guide => <Card key={guide.title} className="p-5"><Link to={guide.path} className="font-semibold text-primary hover:underline">{guide.title}</Link><p className="mt-2 text-sm leading-relaxed text-muted-foreground">{guide.text}</p></Card>)}</div></section>
    <section id="faq" className="scroll-mt-20"><h2 className="text-xl font-semibold mb-4">Frequently asked questions</h2><div className="space-y-3">{filteredFAQs.map(([question, answer]) => <details key={question} className="rounded-xl border bg-card p-5"><summary className="cursor-pointer font-medium">{question}</summary><p className="mt-3 text-sm leading-relaxed text-muted-foreground">{answer}</p></details>)}</div>{!filteredFAQs.length && !filteredGuides.length && <p role="status" className="mt-4 text-sm text-muted-foreground">No matching guides or FAQs. Try “export”, “currency”, or “analytics”.</p>}</section>
    <section id="troubleshooting" className="scroll-mt-20"><h2 className="text-xl font-semibold mb-4">Troubleshooting and data care</h2><Card className="p-6"><ul className="space-y-3 text-sm leading-relaxed text-muted-foreground"><li><strong className="text-foreground">Cannot continue the form?</strong> Enter a positive amount with no commas and up to two decimal places, choose a category, add a description, and select a valid date.</li><li><strong className="text-foreground">Chart or report is empty?</strong> Check the selected month or report period and whether entries are Income or Expense. The donut displays expenses only.</li><li><strong className="text-foreground">Download is missing?</strong> Check your browser's download list and permissions. Clear table selections if you want every filtered row.</li><li><strong className="text-foreground">Data looks different on another device?</strong> Records are local to this browser and website address. Return to the original browser profile; there is no account sync.</li><li><strong className="text-foreground">Before clearing site data:</strong> Download records from Transactions and Reports. Exports provide a reference copy; this version has no restore control.</li><li><strong className="text-foreground">Keyboard:</strong> Press N outside inputs to open Add transaction. Tab moves between controls. Escape closes transaction details and tours. Tour and introduction dialogs prevent accidental shortcut navigation.</li></ul></Card></section>
    <section id="support" className="scroll-mt-20"><h2 className="text-xl font-semibold mb-2">Demo support request</h2><p className="text-sm text-muted-foreground mb-4">A sample local flow: describe an issue, create a demo reference, and download a copy. No email is sent and no live support ticket is created. The request disappears when you leave or reload this page.</p><Card className="p-6 max-w-2xl">{request ? <div role="status" className="space-y-4"><h3 className="font-semibold">Demo request created</h3><p className="text-sm text-muted-foreground">Reference: <span className="font-mono text-foreground">{request.id}</span><br />Status: Local demo only · Not sent</p><dl className="text-sm space-y-2"><div><dt className="text-muted-foreground">Topic</dt><dd>{request.topic}</dd></div><div><dt className="text-muted-foreground">Subject</dt><dd className="break-words">{request.subject}</dd></div><div><dt className="text-muted-foreground">Description</dt><dd className="whitespace-pre-wrap break-words">{request.message}</dd></div></dl><div className="flex flex-wrap gap-3"><Button onClick={downloadRequest}><Download className="h-4 w-4 mr-2" />Download request</Button><Button variant="outline" onClick={() => setRequest(null)}>Edit request</Button></div></div> : <form onSubmit={submit} className="space-y-4"><div className="space-y-2"><Label htmlFor="help-topic">Topic</Label><select id="help-topic" value={topic} onChange={event => setTopic(event.target.value)} className="w-full rounded-md border bg-background px-3 py-2 text-sm">{['Transactions', 'Analytics', 'Reports', 'Data and appearance', 'Other'].map(value => <option key={value}>{value}</option>)}</select></div><div className="space-y-2"><Label htmlFor="help-subject">Subject *</Label><Input id="help-subject" required maxLength={120} value={subject} onChange={event => setSubject(event.target.value)} placeholder="For example: My monthly donut is empty" /></div><div className="space-y-2"><Label htmlFor="help-message">What happened? *</Label><Textarea id="help-message" required maxLength={2000} value={message} onChange={event => setMessage(event.target.value)} placeholder="Describe the screen, steps taken, expected result, and what appeared." /></div>{error && <p role="alert" className="text-sm text-destructive">{error}</p>}<Button type="submit">Create demo request</Button></form>}</Card></section>
  </div>;
}
